version: '3.7'
services:
  react:
    image: portfolio:0.1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8085:80"
    volumes:
      - .docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
