version: "3.8"
services:
  app:
    container_name: app-prod
    image: app-prod-i
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
        - .:/app
    ports:
        - "8080:3000"