version: "3.8"
services:
  app:
    container_name: app-prod
    image: app-prod-i
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
        - .:/app
        - /app/node_modules
        - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
        - "5173:80"
