FROM node:20.11.0-alpine3.18 AS production
ENV NODE_ENV=production

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN set -eux; \
    npm install;

RUN set-eux; \
    npm run build;

# Nginx server
FROM nginx:1.27-alpine as react_nginx

WORKDIR /usr/share/nginx/html

COPY --from=react_build /usr/src/project/dist /usr/share/nginx/html
