version: "3.8"
services:
  app:
    container_name: app-dev
    image: app-dev-i
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
        - .:/app
        - /app/node_modules
    ports:
        - "3001:5173"