FROM node:20.11.0-alpine3.18 AS development
ENV NODE_ENV=development

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN set -eux; \
    npm install;

EXPOSE 3001

CMD ["npm", "run", "dev"]
